/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_qlns;

import java.sql.*;
import java.util.concurrent.locks.Condition;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class dkForm extends javax.swing.JFrame {

    ConnectDB cn = new ConnectDB();
    public dkForm() {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        txtMK = new javax.swing.JPasswordField();
        txtCMK = new javax.swing.JPasswordField();
        btnQuayLai = new javax.swing.JButton();
        btnDk = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTK = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbHienMK = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Thêm tài khoản");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Tài khoản");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Mật khẩu");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu");

        txtTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnQuayLai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnDk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDk.setText("Thêm");
        btnDk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDkActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Thông tin tài khoản nhân viên");

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tbTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNV", "Tài khoản", "Mật khẩu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTK);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("MaNV");

        txtMaNV.setPreferredSize(new java.awt.Dimension(68, 27));

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tìm kiếm:");

        cbHienMK.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        cbHienMK.setText("Hiện mật khẩu");
        cbHienMK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHienMKItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTK)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnDk)
                                .addGap(25, 25, 25)
                                .addComponent(btnSua)
                                .addGap(27, 27, 27)
                                .addComponent(btnXoa))
                            .addComponent(btnQuayLai)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cbHienMK, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHienMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDk)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuayLai))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable() {
        // Xóa dữ liệu hiện có trong bảng
        DefaultTableModel model = (DefaultTableModel) tbTK.getModel();
        model.setRowCount(0);

        // Thực hiện truy vấn lấy dữ liệu từ cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            // Thực hiện truy vấn SELECT để lấy dữ liệu từ bảng NHANVIEN
            String query = "SELECT * FROM TAIKHOAN";
            rs = stmt.executeQuery(query);

            // Đổ dữ liệu từ ResultSet vào bảng
            while (rs.next()) {
                String maNV = rs.getString("MaNV");
                String taiKhoan = rs.getString("TAIKHOAN");
                String matKhau = rs.getString("MATKHAU");

                // Thêm dữ liệu vào bảng
                model.addRow(new Object[]{maNV, taiKhoan, matKhau}); 
            }

            // Đóng ResultSet, câu lệnh và kết nối
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu từ cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void displayDataFromTable(int row) {
        // Lấy dữ liệu từ bảng theo hàng được chọn
        String maNV = tbTK.getValueAt(row, 0).toString();
        String taiKhoan = tbTK.getValueAt(row, 1).toString();
        String matKhau = tbTK.getValueAt(row, 2).toString();
        

        // Hiển thị dữ liệu lên các ô nhập liệu
        txtMaNV.setText(maNV);
        txtTK.setText(taiKhoan);
        txtMK.setText(matKhau);
    }
     
    private boolean KiemTraMk() {
        // Lấy dữ liệu từ các thành phần trên form
        String matKhau = new String(txtMK.getPassword());
        String ConfMatKhau = new String(txtCMK.getPassword());

        // Kiểm tra độ dài
        if (matKhau.length() < 5) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải có độ dài tối thiểu là 5 ký tự!", "Thông báo!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Kiểm tra độ phức tạp
        if (!matKhau.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@#$%^&+=]).{5,}$")) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải chứa ít nhất một ký tự chữ hoa, một ký tự chữ thường, một chữ số và một ký tự đặc biệt!", "Thông báo!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Kiểm tra xem hai mật khẩu có khớp hay không
        if (!matKhau.equals(ConfMatKhau)){
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!", "Thông báo!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Mật khẩu hợp lệ
        return true;
    }

    private void btnDkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDkActionPerformed
        // Lấy dữ liệu từ các thành phần trên form
        String maNV = txtMaNV.getText();
        String taiKhoan = txtTK.getText();
        String matKhau = new String(txtMK.getPassword()); 

        // Thực hiện chèn dữ liệu vào cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();
            
            ResultSet rs = stmt.executeQuery("SELECT MaNV FROM NHANViEN WHERE MaNV = '" + maNV + "';");
            
            if (rs.next()) {
                // Mã nhân viên đã tồn tại
                ResultSet rst = stmt.executeQuery("SELECT TaiKhoan FROM TAIKHOAN WHERE TaiKhoan = '" + taiKhoan + "';");
                if(rst.next()) {
                    // Tài khoản tồn tại
                    JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!", "Thông báo!!!", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Tài khoản không tồn tại
                    // Kiểm tra mật khẩu
                    if (KiemTraMk()) {
                        // Tạo câu truy vấn chèn dữ liệu
                        String query = "INSERT INTO TAIKHOAN (MaNV, TaiKhoan, MatKhau) "
                                + "VALUES ('" + maNV + "', '" + taiKhoan + "', '" + matKhau + "')";

                        // Thực hiện câu truy vấn chèn dữ liệu
                        stmt.executeUpdate(query);

                        // Hiển thị thông báo thành công
                        JOptionPane.showMessageDialog(this, "Đăng ký thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        
                        // Sau khi cập nhật thành công, xóa dữ liệu trong các ô nhập liệu
                        txtMaNV.setText("");
                        txtTK.setText("");
                        txtMK.setText("");
                        txtCMK.setText("");
                    }  
                }
            } else {
                // Mã nhân viên không tồn tại
                JOptionPane.showMessageDialog(this, "Nhân viên không tồn tại!", "Thông báo!!!", JOptionPane.ERROR_MESSAGE);
            }
            
            // Đóng câu lệnh và kết nối
            stmt.close();
            conn.close();
            
            // Tải lại dữ liệu và hiển thị trong bảng
            populateTable();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Nhân viên đã có tài khoản!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDkActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        int tb = JOptionPane.showConfirmDialog(this, "Chắc chắn muốn thoát không!", "Thông báo!!!", JOptionPane.YES_NO_OPTION);
        if (tb != JOptionPane.YES_OPTION){
            return;
        }
        dkForm.this.setVisible(false);
        new MainF().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // Lấy chỉ mục hàng được chọn trong bảng
        int selectedRow = tbTK.getSelectedRow();

        // Kiểm tra xem có hàng nào được chọn không
        if (selectedRow == -1) {
            // Hiển thị thông báo lỗi nếu không có hàng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để sửa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ các thành phần trên form để sửa
        String maNV = txtMaNV.getText();
        String taiKhoan = txtTK.getText();
        String matKhau = new String(txtMK.getPassword());

        // Thực hiện cập nhật dữ liệu vào cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            if (maNV.equals(tbTK.getValueAt(selectedRow, 0))) {
                // MaNV không bị sửa
                // Tạo câu truy vấn cập nhật dữ liệu
                String query = "UPDATE TAIKHOAN SET TaiKhoan = '" + taiKhoan + "', MatKhau = '" + matKhau +
                    "' WHERE MaNV = '" + maNV + "'";

                // Thực hiện câu truy vấn cập nhật dữ liệu
                stmt.executeUpdate(query);

                // Hiển thị thông báo thành công
                JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                // Sau khi cập nhật thành công, xóa dữ liệu trong các ô nhập liệu
                txtMaNV.setText("");
                txtTK.setText("");
                txtMK.setText("");
                txtCMK.setText("");
            } else {
                // MaNV bị sửa
                JOptionPane.showMessageDialog(this, "Không thể sửa mã nhân viên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            
            // Đóng câu lệnh và kết nối
            stmt.close();
            conn.close();
            
            // Tải lại dữ liệu và hiển thị trong bảng
            populateTable();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tbTK.getSelectedRow();

        // Kiểm tra xem có hàng nào được chọn không
        if (selectedRow == -1) {
            // Hiển thị thông báo lỗi nếu không có hàng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ các thành phần trên form để xóa
        String maNV = txtMaNV.getText();

        // Thực hiện cập nhật dữ liệu vào cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            if (!"000".equals(maNV)) {
                // Tạo câu truy vấn cập nhật dữ liệu
                String query = "DELETE FROM TAIKHOAN WHERE MaNV = '" + maNV + "'";

                // Thực hiện câu truy vấn cập nhật dữ liệu
                stmt.executeUpdate(query);

                // Hiển thị thông báo thành công
                JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                // Sau khi cập nhật thành công, xóa dữ liệu trong các ô nhập liệu
                txtMaNV.setText("");
                txtTK.setText("");
                txtMK.setText("");
                txtCMK.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Không thể xóa tài khoản quản trị viên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
                
            // Đóng câu lệnh và kết nối
            stmt.close();
            conn.close();
            
            // Tải lại dữ liệu và hiển thị trong bảng
            populateTable();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTKMouseClicked
        tbTK.setDefaultEditor(Object.class, null);
        tbTK.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Lấy chỉ mục hàng được chọn
                int selectedRow = tbTK.getSelectedRow();
                
                // Hiển thị dữ liệu từ hàng được chọn vào các ô nhập liệu
                displayDataFromTable(selectedRow);
            }
        });
    }//GEN-LAST:event_tbTKMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            // Kết nối đến cơ sở dữ liệu MySQL
            conn = cn.getConnection();

            // Nhập từ khóa tìm kiếm từ người dùng
            String keyword = txtTimKiem.getText();

            // Tạo một câu lệnh truy vấn SQL với điều kiện tìm kiếm
            String query = "SELECT * FROM TAIKHOAN WHERE MaNV LIKE '%" + keyword + "%' OR TaiKhoan LIKE '%" + keyword + "%'" + " OR MatKhau LIKE '%" + keyword + "%'";

            // Tạo một câu lệnh truy vấn SQL
            stmt = conn.createStatement();

            // Thực hiện truy vấn tìm kiếm trong bảng NHANVIEN và lưu kết quả vào ResultSet
            rs = stmt.executeQuery(query);

            // Tạo một DefaultTableModel để lưu dữ liệu từ ResultSet
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("MaNV");
            model.addColumn("Tài Khoản");
            model.addColumn("Mật Khẩu");

            // Đọc dữ liệu từ ResultSet và thêm vào DefaultTableModel
            while (rs.next()) {
                String maNV = rs.getString("MaNV");
                String taiKhoan = rs.getString("TaiKhoan");
                String matKhau = rs.getString("MatKhau");

                Object[] rowData = {maNV, taiKhoan, matKhau};
                model.addRow(rowData);
            }

            // Hiển thị dữ liệu từ DefaultTableModel vào JTable
            tbTK.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Đóng ResultSet, Statement và Connection để giải phóng tài nguyên
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void cbHienMKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHienMKItemStateChanged
        // Kiểm tra xem checkbox được tích hay không
        if (cbHienMK.isSelected()) {
            // Nếu checkbox được tích, thì hiển thị mật khẩu( giá trị \u0000 là giá trị ký tự trống)
            txtMK.setEchoChar('\u0000');
            txtCMK.setEchoChar('\u0000');
        } else {
            // Nếu checkbox không được tích, thì ẩn mật khẩu
            txtMK.setEchoChar('*');
            txtCMK.setEchoChar('*');
        }
    }//GEN-LAST:event_cbHienMKItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dkForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDk;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox cbHienMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTK;
    private javax.swing.JPasswordField txtCMK;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
