/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_qlns;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namta
 */
public class nghiphep extends javax.swing.JFrame {

    /**
     * Creates new form nghiphep
     */
    ConnectDB cn = new ConnectDB();
    DefaultTableModel model;
    public nghiphep() {
        initComponents();
        setupTable();
        loadData();
        
    }
    private void setupTable() {
        // Khởi tạo DefaultTableModel với các cột rỗng và không cho phép chỉnh sửa
        model = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên",
                "Họ tên",
                "Phòng ban",
                "Mã nghỉ phép",
                "Loại nghỉ phép",
                "Ngày bắt đầu",
                "Ngày kết thúc",
                "Lý do",
                "Trạng thái"
            }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào trong bảng
            }
        };

        // Gán model cho JTable dsluong
        dsnghiphep.setModel(model);
    }
    




    private void loadData() {
        
    // Xóa dữ liệu hiện có trong bảng
    DefaultTableModel model = (DefaultTableModel) dsnghiphep.getModel();
    model.setRowCount(0);

    // Thực hiện truy vấn lấy dữ liệu từ cơ sở dữ liệu
    java.sql.Connection conn = null;
    java.sql.Statement stmt = null;
    ResultSet rs = null;

    
    try {
        // Kết nối tới cơ sở dữ liệu
        conn = cn.getConnection();
        
        // Thực hiện truy vấn SQL
        stmt = conn.createStatement();
        String query = """
                       SELECT 
                           nv.MaNV AS `Mã nhân viên`, 
                           nv.HoTen AS `Họ tên`, 
                           pb.TenPB AS `Phòng ban`,
                           np.MaNghiPhep AS `Mã nghỉ phép`, 
                           np.LoaiNghiPhep AS `Loại nghỉ phép`, 
                           np.NgayBatDau AS `Ngày bắt đầu`, 
                           np.NgayKetThuc AS `Ngày kết thúc`, 
                           np.LyDo AS `Lý do`, 
                           np.TrangThai AS `Trạng thái`
                       FROM 
                           nhanvien nv
                       JOIN 
                           phongban pb ON nv.MaPB = pb.MaPB
                       JOIN 
                           nghiphep np ON nv.MaNV = np.MaNV;
                       """;
        rs = stmt.executeQuery(query);

        // Xóa dữ liệu cũ trong bảng
        model.setRowCount(0);

        // Lặp qua kết quả truy vấn và thêm vào mô hình bảng
        while (rs.next()) {
            Object[] row = {
                    rs.getString("Mã nhân viên"),
                    rs.getString("Họ tên"),
                    rs.getString("Phòng ban"),
                    rs.getString("Mã nghỉ phép"),
                    rs.getString("Loại nghỉ phép"),
                    rs.getString("Ngày bắt đầu"),
                    rs.getString("Ngày kết thúc"),
                    rs.getString("Lý do"),
                    rs.getString("Trạng thái")};
            model.addRow(row);
            
        }
    } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu từ cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_manp = new javax.swing.JTextField();
        txt_mnv = new javax.swing.JTextField();
        txt_nbd = new javax.swing.JTextField();
        txt_nkt = new javax.swing.JTextField();
        txt_lnp = new javax.swing.JTextField();
        txt_ld = new javax.swing.JTextField();
        txt_tt = new javax.swing.JTextField();
        btn_luu = new javax.swing.JButton();
        btn_capnhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsnghiphep = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Mã nhân viên");

        jLabel5.setText("Mã nghỉ phép");

        jLabel6.setText("Loại nghỉ phép");

        jLabel7.setText("Ngày bắt đầu");

        jLabel8.setText("Ngày kết thúc");

        jLabel9.setText("Lý do");

        jLabel10.setText("Trạng thái");

        btn_luu.setText("lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_capnhat.setText("Cập nhật ");
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        btn_xoa.setText("xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_manp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_mnv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nbd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_lnp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(txt_nkt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_luu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_capnhat)
                                .addGap(18, 18, 18)
                                .addComponent(btn_xoa)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_manp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_mnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_luu)
                    .addComponent(btn_capnhat)
                    .addComponent(btn_xoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dsnghiphep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nghỉ phép", "Mã nhân viên", "Họ tên", "Phòng ban", "Loại nghỉ phép", "Ngày bắt đầu", "Ngày kết thúc", "Lý do", "Trạng thái"
            }
        ));
        dsnghiphep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsnghiphepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsnghiphep);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nghỉ phép");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dsnghiphepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsnghiphepMouseClicked
        // TODO add your handling code here:
        int selectedRow = dsnghiphep.getSelectedRow();
        if (selectedRow != -1) {
            txt_mnv.setText(model.getValueAt(selectedRow, 0).toString());
            txt_manp.setText(model.getValueAt(selectedRow, 3).toString());
            txt_lnp.setText(model.getValueAt(selectedRow, 4).toString());
            txt_nbd.setText(model.getValueAt(selectedRow, 5).toString());
            txt_nkt.setText(model.getValueAt(selectedRow, 6).toString());
            txt_ld.setText(model.getValueAt(selectedRow, 7).toString());
            txt_tt.setText(model.getValueAt(selectedRow, 8).toString());
        }
    }//GEN-LAST:event_dsnghiphepMouseClicked

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        String maNghiPhep = txt_manp.getText();
        String maNV = txt_mnv.getText();
        String loaiNghiPhep = txt_lnp.getText();
        String ngayBatDau = txt_nbd.getText();
        String ngayKetThuc = txt_nkt.getText();
        String lyDo = txt_ld.getText();
        String trangThai = txt_tt.getText();    
     
     

     // Chuỗi câu truy vấn SQL
     String insertQuery = "INSERT INTO nghiphep (MaNghiPhep, MaNV, LoaiNghiPhep, NgayBatDau, NgayKetThuc, LyDo, TrangThai) VALUES (?, ?, ?, ?, ?, ?, ?)";

     try {
         java.sql.Connection conn = cn.getConnection(); // Thiết lập kết nối

         if (!maNghiPhep.isEmpty()) {  // Kiểm tra xem maLuong có rỗng hay không
             // Thêm bản ghi mới
             try (PreparedStatement pstmt = conn.prepareStatement(insertQuery)) {
                 pstmt.setString(1, maNghiPhep);
                    pstmt.setString(2, maNV);
                    pstmt.setString(3, loaiNghiPhep);
                    pstmt.setString(4, ngayBatDau);
                    pstmt.setString(5, ngayKetThuc);
                    pstmt.setString(6, lyDo);
                    pstmt.setString(7, trangThai);
                 pstmt.executeUpdate();
                 System.out.println("Câu truy vấn thêm thực thi thành công!");
             }
         } 

         // Tải lại dữ liệu sau khi cập nhật/thêm
         loadData();
         JOptionPane.showMessageDialog(this, "Lưu thành công!");

     } catch (SQLException e) {
         JOptionPane.showMessageDialog(this, "Lỗi khi lưu vào cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
         // Lấy giá trị đầu vào từ các ô nhập liệu
    String maNghiPhep = txt_manp.getText();

    // Chuỗi câu truy vấn SQL
    String deleteQuery = "DELETE FROM nghiphep WHERE MaNghiPhep = ?";

    try {
        java.sql.Connection conn = cn.getConnection(); // Thiết lập kết nối

        if (!maNghiPhep.isEmpty()) {
            // Thực thi câu truy vấn xóa
            try (PreparedStatement pstmt = conn.prepareStatement(deleteQuery)) {
                pstmt.setString(1, maNghiPhep);

                int affectedRows = pstmt.executeUpdate();
                if (affectedRows > 0) {
                    System.out.println("Xóa thành công!");
                } else {
                    System.out.println("Không tìm thấy dữ liệu để xóa!");
                }
            }
        } else {
            System.out.println("MaNghiPhep không được để trống!");
        }

        // Tải lại dữ liệu sau khi xóa
        loadData();
        JOptionPane.showMessageDialog(this, "Xóa thành công!");

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa dữ liệu từ cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here:
        // Lấy giá trị đầu vào từ các ô nhập liệu
    String maNghiPhep = txt_manp.getText();
    String maNV = txt_mnv.getText();
    String loaiNghiPhep = txt_lnp.getText();
    String ngayBatDau = txt_nbd.getText();
    String ngayKetThuc = txt_nkt.getText();
    String lyDo = txt_ld.getText();
    String trangThai = txt_tt.getText();

    // Chuỗi câu truy vấn SQL
    String updateQuery = "UPDATE nghiphep SET MaNV = ?, LoaiNghiPhep = ?, NgayBatDau = ?, NgayKetThuc = ?, LyDo = ?, TrangThai = ? " +
                         "WHERE MaNghiPhep = ?";

    try {
        java.sql.Connection conn = cn.getConnection(); // Thiết lập kết nối

        // Cập nhật bản ghi
        try (PreparedStatement pstmt = conn.prepareStatement(updateQuery)) {
            pstmt.setString(1, maNV);
            pstmt.setString(2, loaiNghiPhep);
            pstmt.setString(3, ngayBatDau);
            pstmt.setString(4, ngayKetThuc);
            pstmt.setString(5, lyDo);
            pstmt.setString(6, trangThai);
            pstmt.setString(7, maNghiPhep);
            pstmt.executeUpdate();
            System.out.println("Cập nhật thành công!");
        }

        // Tải lại dữ liệu sau khi cập nhật/thêm
        loadData();
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu vào cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_capnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nghiphep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nghiphep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nghiphep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nghiphep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nghiphep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhat;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JTable dsnghiphep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_ld;
    private javax.swing.JTextField txt_lnp;
    private javax.swing.JTextField txt_manp;
    private javax.swing.JTextField txt_mnv;
    private javax.swing.JTextField txt_nbd;
    private javax.swing.JTextField txt_nkt;
    private javax.swing.JTextField txt_tt;
    // End of variables declaration//GEN-END:variables
}
