/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_qlns;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ThongTinForm extends javax.swing.JFrame {

    ConnectDB cn = new ConnectDB();
    public ThongTinForm() {
        initComponents();
        
        populateTable();
        
        TablePB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMaPB = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTin = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPB = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin nhân viên");

        jLabel2.setText("MaNV:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("Giới tính:");

        jLabel6.setText("Quê quán:");

        jLabel7.setText("Số điện thoại:");

        jLabel8.setText("Email:");

        jLabel9.setText("MaPB:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        tbThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNV", "Họ tên", "Ngày sinh", "Giới tính", "Quê quán", "SĐT", "Email", "Tên PB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTin);
        if (tbThongTin.getColumnModel().getColumnCount() > 0) {
            tbThongTin.getColumnModel().getColumn(0).setMinWidth(50);
            tbThongTin.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbThongTin.getColumnModel().getColumn(0).setMaxWidth(50);
            tbThongTin.getColumnModel().getColumn(1).setMinWidth(0);
            tbThongTin.getColumnModel().getColumn(1).setPreferredWidth(2500);
            tbThongTin.getColumnModel().getColumn(1).setMaxWidth(3000);
            tbThongTin.getColumnModel().getColumn(2).setMinWidth(0);
            tbThongTin.getColumnModel().getColumn(2).setPreferredWidth(1000);
            tbThongTin.getColumnModel().getColumn(2).setMaxWidth(1500);
            tbThongTin.getColumnModel().getColumn(3).setMinWidth(0);
            tbThongTin.getColumnModel().getColumn(3).setPreferredWidth(1000);
            tbThongTin.getColumnModel().getColumn(3).setMaxWidth(1500);
            tbThongTin.getColumnModel().getColumn(4).setMinWidth(0);
            tbThongTin.getColumnModel().getColumn(4).setPreferredWidth(2000);
            tbThongTin.getColumnModel().getColumn(4).setMaxWidth(5000);
            tbThongTin.getColumnModel().getColumn(5).setMinWidth(0);
            tbThongTin.getColumnModel().getColumn(5).setPreferredWidth(1000);
            tbThongTin.getColumnModel().getColumn(5).setMaxWidth(1500);
            tbThongTin.getColumnModel().getColumn(6).setMinWidth(0);
            tbThongTin.getColumnModel().getColumn(6).setPreferredWidth(2500);
            tbThongTin.getColumnModel().getColumn(6).setMaxWidth(3000);
            tbThongTin.getColumnModel().getColumn(7).setMinWidth(50);
            tbThongTin.getColumnModel().getColumn(7).setPreferredWidth(500);
            tbThongTin.getColumnModel().getColumn(7).setMaxWidth(500);
        }

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        tbPB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaPB", "Tên PB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPBMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPB);
        if (tbPB.getColumnModel().getColumnCount() > 0) {
            tbPB.getColumnModel().getColumn(0).setPreferredWidth(500);
            tbPB.getColumnModel().getColumn(0).setMaxWidth(500);
            tbPB.getColumnModel().getColumn(1).setMinWidth(50);
            tbPB.getColumnModel().getColumn(1).setPreferredWidth(500);
            tbPB.getColumnModel().getColumn(1).setMaxWidth(1000);
        }

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Thông tin phòng ban");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel11)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(1, 1, 1)))
                .addGap(5, 5, 5))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThem)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(83, 83, 83)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa)
                                .addGap(50, 50, 50)
                                .addComponent(btnQuayLai))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void TablePB(){
        // Xóa dữ liệu hiện có trong bảng
        DefaultTableModel model = (DefaultTableModel) tbPB.getModel();
        model.setRowCount(0);

        // Thực hiện truy vấn lấy dữ liệu từ cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        
        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            // Thay đổi câu truy vấn
            String query = "SELECT * FROM phongban;";
            rs = stmt.executeQuery(query);

            // Đổ dữ liệu từ ResultSet vào bảng
            while (rs.next()) {
                String maNV = rs.getString("MaPB");
                String tenPB = rs.getString("TenPB");

                // Thêm dữ liệu vào bảng
                model.addRow(new Object[]{maNV, tenPB});
            }

            // Đóng ResultSet, câu lệnh và kết nối
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu từ cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        int tb = JOptionPane.showConfirmDialog(this, "Chắc chắn muốn thoát không!", "Thông báo!!!", JOptionPane.YES_NO_OPTION);
        if (tb != JOptionPane.YES_OPTION){
            return;
        }
        ThongTinForm.this.setVisible(false);
        new MainF().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Lấy dữ liệu từ các thành phần trên form
        String maNV = txtMaNV.getText();
        String hoTen = txtHoTen.getText();
        String ngaySinh = txtNgaySinh.getText();
        String gioiTinh = cbGioiTinh.getSelectedItem().toString();
        String diaChi = txtDiaChi.getText();
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        String maPB = txtMaPB.getText();


        // Kiểm tra xem các ô dữ liệu có trống hay không
        if (maNV.isEmpty() || hoTen.isEmpty() || ngaySinh.isEmpty() || gioiTinh.isEmpty() || diaChi.isEmpty() || sdt.isEmpty() || email.isEmpty() || maPB.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống bất kỳ thông tin nào!", "Thông báo!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Thực hiện chèn dữ liệu vào cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            // Tạo và thực hiện câu truy vấn
            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS SoLuong FROM PHONGBAN WHERE MaPB = '" + maPB + "'");
            
            // Lấy kết quả
            rs.next();
            int soLuong = rs.getInt("SoLuong");

            // Nếu mã phòng ban không tồn tại thì hiển thị thông báo
            if (soLuong == 0) {
                JOptionPane.showMessageDialog(this, "Mã phòng ban không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Tạo câu truy vấn chèn dữ liệu
            String query = "INSERT INTO NHANVIEN (MaNV, HoTen, NgaySinh, GioiTinh, DiaChi, SoDienThoai, Email, MaPB) "
                    + "VALUES ('" + maNV + "', '" + hoTen + "', '" + ngaySinh + "', '" + gioiTinh + "', '" + diaChi + "', '" + sdt + "', '" 
                    + email + "', '" + maPB + "')";

            // Thực hiện câu truy vấn chèn dữ liệu
            stmt.executeUpdate(query);

            // Hiển thị thông báo thành công
            JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            
            // Sau khi cập nhật thành công, xóa dữ liệu trong các ô nhập liệu
            txtMaNV.setText("");
            txtHoTen.setText("");
            txtNgaySinh.setText("");
            cbGioiTinh.setSelectedIndex(0);
            txtDiaChi.setText("");
            txtSDT.setText("");
            txtEmail.setText("");
            txtMaPB.setText("");
            
            // Đóng câu lệnh và kết nối
            stmt.close();
            conn.close();
            
            // Tải lại dữ liệu và hiển thị trong bảng
            populateTable();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed
    
    private void populateTable() {
        // Xóa dữ liệu hiện có trong bảng
        DefaultTableModel model = (DefaultTableModel) tbThongTin.getModel();
        model.setRowCount(0);

        // Thực hiện truy vấn lấy dữ liệu từ cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            // Thay đổi câu truy vấn
            String query = "SELECT nhanvien.*, phongban.TenPB "
                    + "FROM nhanvien "
                    + "JOIN phongban "
                    + "ON nhanvien.MaPB = phongban.MaPB;";
            rs = stmt.executeQuery(query);

            // Đổ dữ liệu từ ResultSet vào bảng
            while (rs.next()) {
                String maNV = rs.getString("MaNV");
                String hoTen = rs.getString("HoTen");
                String ngaySinh = rs.getString("NgaySinh");
                String gioiTinh = rs.getString("GioiTinh");
                String diaChi = rs.getString("DiaChi");
                String sdt = rs.getString("SoDienThoai");
                String email = rs.getString("Email");
                String tenPB = rs.getString("TenPB");

                // Thêm dữ liệu vào bảng
                model.addRow(new Object[]{maNV, hoTen, ngaySinh, gioiTinh, diaChi, sdt, email, tenPB});
            }

            // Đóng ResultSet, câu lệnh và kết nối
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu từ cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // Lấy chỉ mục hàng được chọn trong bảng
        int selectedRow = tbThongTin.getSelectedRow();

        // Kiểm tra xem có hàng nào được chọn không
        if (selectedRow == -1) {
            // Hiển thị thông báo lỗi nếu không có hàng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để sửa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ các thành phần trên form để sửa
        String maNV = txtMaNV.getText();
        String hoTen = txtHoTen.getText();
        String ngaySinh = txtNgaySinh.getText();
        String gioiTinh = cbGioiTinh.getSelectedItem().toString();
        String diaChi = txtDiaChi.getText();
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        String maPB = txtMaPB.getText();

        // Thực hiện cập nhật dữ liệu vào cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            if (maNV.equals(tbThongTin.getValueAt(selectedRow, 0))) {
                // MaNV không bị sửa
                
                // Tạo và thực hiện câu truy vấn
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS SoLuong FROM PHONGBAN WHERE MaPB = '" + maPB + "'");

                // Lấy kết quả
                rs.next();
                int soLuong = rs.getInt("SoLuong");

                // Nếu mã phòng ban không tồn tại thì hiển thị thông báo
                if (soLuong == 0) {
                    JOptionPane.showMessageDialog(this, "Mã phòng ban không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                // Tạo câu truy vấn cập nhật dữ liệu
                String query = "UPDATE NHANVIEN SET HoTen = '" + hoTen + "', NgaySinh = '" + ngaySinh + "', GioiTinh = '" + gioiTinh + "', DiaChi = '" 
                        + diaChi + "', SoDienThoai = '" + sdt + "', Email = '" + email + "', MaPB = '" + maPB + "' WHERE MaNV = '" + maNV + "'";

                // Thực hiện câu truy vấn cập nhật dữ liệu
                stmt.executeUpdate(query);

                // Hiển thị thông báo thành công
                JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                // Sau khi cập nhật thành công, xóa dữ liệu trong các ô nhập liệu
                txtMaNV.setText("");
                txtHoTen.setText("");
                txtNgaySinh.setText("");
                cbGioiTinh.setSelectedIndex(0);
                txtDiaChi.setText("");
                txtSDT.setText("");
                txtEmail.setText("");
                txtMaPB.setText("");
            } else {
                // MaNV bị sửa
                JOptionPane.showMessageDialog(this, "Không thể sửa MaNV !", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
                   
            // Đóng câu lệnh và kết nối
            stmt.close();
            conn.close();
            
            // Tải lại dữ liệu và hiển thị trong bảng
            populateTable();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void displayDataFromTable(int row) {
        // Lấy dữ liệu từ bảng theo hàng được chọn
        String maNV = tbThongTin.getValueAt(row, 0).toString();
        String hoTen = tbThongTin.getValueAt(row, 1).toString();
        String ngaySinh = tbThongTin.getValueAt(row, 2).toString();
        String gioiTinh = tbThongTin.getValueAt(row, 3).toString();
        String diaChi = tbThongTin.getValueAt(row, 4).toString();
        String soDienThoai = tbThongTin.getValueAt(row, 5).toString();
        String email = tbThongTin.getValueAt(row, 6).toString();

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        String maPB = "";

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            // Tạo câu truy vấn lấy mã phòng ban
            String query = "SELECT MaPB "
                    + "FROM PHONGBAN "
                    + "WHERE TenPB = '" + tbThongTin.getValueAt(row, 7).toString() + "'";

            // Thực hiện câu truy vấn
            rs = stmt.executeQuery(query);

            // Lấy kết quả
            if (rs.next()) {
                maPB = rs.getString("MaPB");
            }

            // Đóng câu lệnh và kết nối
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
        // Hiển thị dữ liệu lên các ô nhập liệu
        txtMaNV.setText(maNV);
        txtHoTen.setText(hoTen);
        txtNgaySinh.setText(ngaySinh);
        cbGioiTinh.setSelectedItem(gioiTinh);
        txtDiaChi.setText(diaChi);
        txtSDT.setText(soDienThoai);
        txtEmail.setText(email);
        txtMaPB.setText(maPB);
    }
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tbThongTin.getSelectedRow();

        // Kiểm tra xem có hàng nào được chọn không
        if (selectedRow == -1) {
            // Hiển thị thông báo lỗi nếu không có hàng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ các thành phần trên form để xóa
        String maNV = txtMaNV.getText();

        // Thực hiện cập nhật dữ liệu vào cơ sở dữ liệu
        Connection conn = null;
        Statement stmt = null;

        try {
            // Thiết lập kết nối
            conn = cn.getConnection();
            stmt = conn.createStatement();

            // Tạo câu truy vấn cập nhật dữ liệu
            String query = "DELETE FROM NHANVIEN WHERE MaNV = '" + maNV + "'";

            // Thực hiện câu truy vấn cập nhật dữ liệu
            stmt.executeUpdate(query);

            // Đóng câu lệnh và kết nối
            stmt.close();
            conn.close();

            // Hiển thị thông báo thành công
            JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            
            // Sau khi cập nhật thành công, xóa dữ liệu trong các ô nhập liệu
            txtMaNV.setText("");
            txtHoTen.setText("");
            txtNgaySinh.setText("");
            cbGioiTinh.setSelectedIndex(0);
            txtDiaChi.setText("");
            txtSDT.setText("");
            txtEmail.setText("");
            txtMaPB.setText("");
            
            // Tải lại dữ liệu và hiển thị trong bảng
            populateTable();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // Kiểm tra xem ô tìm kiếm có trống hay không
        if (txtTimKiem.getText().isEmpty()) {
            // Load lại bảng
            populateTable();
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tbThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinMouseClicked
        tbThongTin.setDefaultEditor(Object.class, null);
        tbThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Lấy chỉ mục hàng được chọn
                int selectedRow = tbThongTin.getSelectedRow();
                
                // Hiển thị dữ liệu từ hàng được chọn vào các ô nhập liệu
                displayDataFromTable(selectedRow);
            }
        });
    }//GEN-LAST:event_tbThongTinMouseClicked

    private void tbPBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPBMouseClicked
        tbPB.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tbPBMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            // Kết nối đến cơ sở dữ liệu MySQL
            conn = cn.getConnection();

            // Nhập từ khóa tìm kiếm từ người dùng
            String keyword = txtTimKiem.getText();

            // Tạo một câu lệnh truy vấn SQL với điều kiện tìm kiếm
            String query = "SELECT * FROM NHANVIEN, PHONGBAN "
            + "WHERE NHANVIEN.MaPB = PHONGBAN.MaPB AND (HoTen LIKE '%" + keyword + "%' OR MaNV LIKE '%" + keyword + "%'"
            + " OR GioiTinh LIKE '%" + keyword + "%' OR NgaySinh LIKE '%" + keyword + "%'"
            + " OR DiaChi LIKE '%" + keyword + "%' OR SoDienThoai LIKE '%" + keyword + "%'"
            + " OR Email LIKE '%" + keyword + "%' OR TenPB LIKE '%" + keyword + "%')";

            // Tạo một câu lệnh truy vấn SQL
            stmt = conn.createStatement();

            // Thực hiện truy vấn tìm kiếm trong bảng NHANVIEN và lưu kết quả vào ResultSet
            rs = stmt.executeQuery(query);

            // Kiểm tra xem có kết quả tìm kiếm hay không
            if (!rs.isBeforeFirst()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Tạo một DefaultTableModel để lưu dữ liệu từ ResultSet
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("MaNV");
                model.addColumn("Họ tên");
                model.addColumn("Ngày sinh");
                model.addColumn("Giới tính");
                model.addColumn("Địa chỉ");
                model.addColumn("Số điện thoại");
                model.addColumn("Email");
                model.addColumn("Tên PB");

                // Đọc dữ liệu từ ResultSet và thêm vào DefaultTableModel
                while (rs.next()) {
                    String maNV = rs.getString("MaNV");
                    String hoTen = rs.getString("HoTen");
                    Date ngaySinh = rs.getDate("NgaySinh");
                    String gioiTinh = rs.getString("GioiTinh");
                    String diaChi = rs.getString("DiaChi");
                    String soDienThoai = rs.getString("SoDienThoai");
                    String email = rs.getString("Email");
                    String PB = rs.getString("TenPB");

                    Object[] rowData = {maNV, hoTen, ngaySinh, gioiTinh, diaChi, soDienThoai, email, PB};
                    model.addRow(rowData);
                }

                // Hiển thị dữ liệu từ DefaultTableModel vào JTable
                tbThongTin.setModel(model);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Đóng ResultSet, Statement và Connection để giải phóng tài nguyên
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinForm().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbPB;
    private javax.swing.JTable tbThongTin;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaPB;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
